#Make sure you have both <ep> in display_name and valid filename_regex. Other wise OKP will not match your ep number.
display_name="【喵萌奶茶屋】★01月新番★[迷宫饭 / Dungeon Meshi / Delicious in Dungeon][<ep>][<res>p][简日双语][招募翻译时轴]"
group_name="[喵萌奶茶屋]"
poster="https://s2.loli.net/2024/01/05/ShBtOI7zqiN5ayw.webp"
about="https://github.com/Nekomoekissaten-SUB"
# Use ''' to avoid escape
filename_regex='''\]\[(?<ep>\d{2})\]\['''
resolution_regex='''\]\[(?<res>\d{3}|\d{4})p\]\['''
tags=["Anime", "TV"]

[[intro_template]]
site="nyaa"
name="nekomoekissaten"

[[intro_template]]
site="dmhy"
name="喵萌奶茶屋"

[[intro_template]]
site="acgrip"
name="喵萌奶茶屋"

# [[intro_template]]
# site="bangumi"
# name="喵萌奶茶屋"

# [[intro_template]]
# site="acgnx_asia"
# name="174"

# [[intro_template]]
# site="acgnx_global"
# name="212"